[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "9a8Q4589kbV4yRPyMQVg4x47KqdgSkkzBkQfgidNWjcW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/grajnikanth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
